const cheerio = require('cheerio');
const fs = require('fs-extra');
const path = require('path');

class HtmlParserService {
  constructor() {
    this.sectionKeywords = {
      experience: ['experience', 'work history', 'employment', 'professional experience'],
      education: ['education', 'academic', 'qualification', 'degree'],
      skills: ['skills', 'technical skills', 'competencies', 'technologies'],
      projects: ['projects', 'portfolio', 'personal projects'],
      contact: ['email', 'phone', 'linkedin', 'github', 'address']
    };
  }

  /**
   * Parse HTML generated by pdf2htmlEX
   * @param {string} htmlPath - Path to HTML file
   * @returns {Promise<Object>} - Parsed resume data
   */
  async parseResumeHtml(htmlPath) {
    try {
      const html = await fs.readFile(htmlPath, 'utf-8');
      const $ = cheerio.load(html);
      
      // Extract text blocks with positions
      const textBlocks = [];
      let blockId = 0;
      
      // pdf2htmlEX uses .pc for page containers and .t for text elements
      $('.pc').each((pageIndex, page) => {
        const $page = $(page);
        const pageHeight = this.extractPixelValue($page.css('height'));
        
        $page.find('.t').each((index, element) => {
          const $el = $(element);
          const text = $el.text().trim();
          
          if (text) {
            textBlocks.push({
              id: `text-${pageIndex}-${blockId++}`,
              text: text,
              html: $.html(element),
              pageIndex: pageIndex,
              position: {
                left: this.extractPixelValue($el.css('left')),
                top: this.extractPixelValue($el.css('top')),
                width: this.extractPixelValue($el.css('width')),
                height: this.extractPixelValue($el.css('height'))
              },
              styles: $el.attr('style') || '',
              fontSize: this.extractFontSize($el),
              fontWeight: this.extractFontWeight($el),
              className: $el.attr('class') || ''
            });
          }
        });
      });
      
      // Sort blocks by position (top to bottom, left to right)
      textBlocks.sort((a, b) => {
        const pageDiff = a.pageIndex - b.pageIndex;
        if (pageDiff !== 0) return pageDiff;
        
        const topDiff = a.position.top - b.position.top;
        if (Math.abs(topDiff) > 5) return topDiff;
        
        return a.position.left - b.position.left;
      });
      
      return {
        fullHtml: html,
        textBlocks: textBlocks,
        documentStructure: this.categorizeTextBlocks(textBlocks),
        metadata: {
          totalPages: $('.pc').length,
          totalBlocks: textBlocks.length
        }
      };
    } catch (error) {
      console.error('Error parsing HTML:', error);
      throw new Error(`Failed to parse HTML: ${error.message}`);
    }
  }

  /**
   * Categorize text blocks into resume sections
   * @param {Array} textBlocks - Array of text blocks
   * @returns {Object} - Categorized structure
   */
  categorizeTextBlocks(textBlocks) {
    const structure = {
      name: null,
      contact: [],
      sections: []
    };
    
    if (textBlocks.length === 0) return structure;
    
    let currentSection = null;
    let sectionStartIndex = 0;
    
    textBlocks.forEach((block, index) => {
      const text = block.text.toLowerCase();
      const isHeader = this.isHeader(block, textBlocks);
      
      // First block is often the name
      if (index === 0 && !this.looksLikeContact(text)) {
        structure.name = block;
        return;
      }
      
      // Check for contact information
      if (this.looksLikeContact(text)) {
        structure.contact.push(block);
        return;
      }
      
      // Check for section headers
      if (isHeader) {
        // Save previous section
        if (currentSection) {
          currentSection.blocks = textBlocks.slice(sectionStartIndex, index);
          structure.sections.push(currentSection);
        }
        
        // Start new section
        currentSection = {
          title: block.text,
          type: this.identifySectionType(text),
          titleBlock: block,
          blocks: []
        };
        sectionStartIndex = index + 1;
      }
    });
    
    // Save last section
    if (currentSection) {
      currentSection.blocks = textBlocks.slice(sectionStartIndex);
      structure.sections.push(currentSection);
    }
    
    // Identify bullet points and sub-items
    structure.sections.forEach(section => {
      section.items = this.extractSectionItems(section.blocks);
    });
    
    return structure;
  }

  /**
   * Determine if a block is a header based on formatting
   * @param {Object} block - Text block
   * @param {Array} allBlocks - All text blocks
   * @returns {boolean}
   */
  isHeader(block, allBlocks) {
    // Headers typically have larger font size or are in all caps
    const avgFontSize = allBlocks.reduce((sum, b) => sum + (b.fontSize || 10), 0) / allBlocks.length;
    const isLargerFont = block.fontSize > avgFontSize * 1.2;
    const isAllCaps = block.text === block.text.toUpperCase() && block.text.length > 2;
    const isBold = block.fontWeight > 400;
    
    // Check if it matches section keywords
    const matchesKeyword = Object.values(this.sectionKeywords).flat()
      .some(keyword => block.text.toLowerCase().includes(keyword));
    
    return (isLargerFont || isAllCaps || isBold) && matchesKeyword;
  }

  /**
   * Identify section type based on text
   * @param {string} text - Section header text
   * @returns {string} - Section type
   */
  identifySectionType(text) {
    const lowerText = text.toLowerCase();
    
    for (const [type, keywords] of Object.entries(this.sectionKeywords)) {
      if (keywords.some(keyword => lowerText.includes(keyword))) {
        return type;
      }
    }
    
    return 'other';
  }

  /**
   * Check if text looks like contact information
   * @param {string} text - Text to check
   * @returns {boolean}
   */
  looksLikeContact(text) {
    const patterns = [
      /\b[\w._%+-]+@[\w.-]+\.[A-Z|a-z]{2,}\b/, // Email
      /\b\d{3}[-.]?\d{3}[-.]?\d{4}\b/, // Phone
      /\b(linkedin|github|portfolio)\b/i, // Social links
      /\b(http|https|www)\b/i // URLs
    ];
    
    return patterns.some(pattern => pattern.test(text));
  }

  /**
   * Extract structured items from section blocks
   * @param {Array} blocks - Section blocks
   * @returns {Array} - Structured items
   */
  extractSectionItems(blocks) {
    const items = [];
    let currentItem = null;
    
    blocks.forEach(block => {
      const text = block.text;
      const isBullet = text.startsWith('•') || text.startsWith('◦') || text.startsWith('-');
      const isDate = /\b\d{4}\b|\b(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)/i.test(text);
      
      if (isBullet) {
        if (currentItem) {
          items.push(currentItem);
        }
        currentItem = {
          type: 'bullet',
          blocks: [block],
          text: text.replace(/^[•◦-]\s*/, '')
        };
      } else if (isDate && currentItem) {
        currentItem.date = block;
      } else if (currentItem && block.position.left > currentItem.blocks[0].position.left + 20) {
        // Indented text is part of previous item
        currentItem.blocks.push(block);
      } else {
        if (currentItem) {
          items.push(currentItem);
        }
        currentItem = {
          type: 'text',
          blocks: [block],
          text: text
        };
      }
    });
    
    if (currentItem) {
      items.push(currentItem);
    }
    
    return items;
  }

  /**
   * Rebuild HTML with modifications
   * @param {string} originalHtml - Original HTML
   * @param {Array} modifications - Array of modifications
   * @returns {string} - Modified HTML
   */
  rebuildHtml(originalHtml, modifications) {
    const $ = cheerio.load(originalHtml);
    
    modifications.forEach(mod => {
      // Find all text elements
      $('.t').each((i, el) => {
        const $el = $(el);
        const elementText = $el.text().trim();
        
        if (elementText === mod.originalText.trim()) {
          if (mod.newText) {
            // Replace text content while preserving formatting
            $el.text(mod.newText);
          }
          
          if (mod.styles) {
            $el.attr('style', mod.styles);
          }
          
          if (mod.addClass) {
            $el.addClass(mod.addClass);
          }
        }
      });
    });
    
    return $.html();
  }

  /**
   * Extract pixel value from CSS
   * @param {string} cssValue - CSS value like "10px"
   * @returns {number} - Numeric value
   */
  extractPixelValue(cssValue) {
    if (!cssValue) return 0;
    const match = cssValue.match(/(-?\d+(?:\.\d+)?)/);
    return match ? parseFloat(match[1]) : 0;
  }

  /**
   * Extract font size from element
   * @param {Object} $el - Cheerio element
   * @returns {number} - Font size in pixels
   */
  extractFontSize($el) {
    const style = $el.attr('style') || '';
    const fontSizeMatch = style.match(/font-size:\s*(\d+(?:\.\d+)?)px/);
    if (fontSizeMatch) {
      return parseFloat(fontSizeMatch[1]);
    }
    
    // Check class for font size
    const className = $el.attr('class') || '';
    const classMatch = className.match(/fs(\d+)/);
    return classMatch ? parseInt(classMatch[1]) : 12;
  }

  /**
   * Extract font weight from element
   * @param {Object} $el - Cheerio element
   * @returns {number} - Font weight
   */
  extractFontWeight($el) {
    const style = $el.attr('style') || '';
    const fontWeightMatch = style.match(/font-weight:\s*(\d+|bold)/);
    if (fontWeightMatch) {
      return fontWeightMatch[1] === 'bold' ? 700 : parseInt(fontWeightMatch[1]);
    }
    return 400;
  }

  /**
   * Find text blocks by content
   * @param {Array} textBlocks - All text blocks
   * @param {string} searchText - Text to search for
   * @returns {Array} - Matching blocks
   */
  findBlocksByText(textBlocks, searchText) {
    const normalizedSearch = searchText.toLowerCase().trim();
    return textBlocks.filter(block => 
      block.text.toLowerCase().includes(normalizedSearch)
    );
  }

  /**
   * Get blocks in a specific region
   * @param {Array} textBlocks - All text blocks
   * @param {Object} region - Region bounds {left, top, right, bottom}
   * @returns {Array} - Blocks in region
   */
  getBlocksInRegion(textBlocks, region) {
    return textBlocks.filter(block => {
      const pos = block.position;
      return pos.left >= region.left &&
             pos.top >= region.top &&
             pos.left + pos.width <= region.right &&
             pos.top + pos.height <= region.bottom;
    });
  }

  /**
   * Apply AI suggestions to HTML with tracking
   * @param {string} originalHtml - Original HTML from pdf2htmlEX
   * @param {Array} mappedSuggestions - Mapped suggestions from textMatcher
   * @returns {string} - Modified HTML with suggestions
   */
  applySuggestionsToHtml(originalHtml, mappedSuggestions) {
    const $ = cheerio.load(originalHtml);
    let suggestionCount = 0;
    
    // First, ensure all text elements have IDs
    $('.t').each((index, element) => {
      const $el = $(element);
      if (!$el.attr('id')) {
        $el.attr('id', `text-auto-${index}`);
      }
    });
    
    // Apply suggestions
    for (const suggestion of mappedSuggestions) {
      // Try multiple selection strategies
      let $element = null;
      
      // Strategy 1: Direct ID match
      if (suggestion.blockId) {
        $element = $(`#${suggestion.blockId}`);
      }
      
      // Strategy 2: Find by exact text match
      if (!$element || !$element.length) {
        $('.t').each((i, el) => {
          const $el = $(el);
          if ($el.text().trim() === suggestion.originalText.trim()) {
            $element = $el;
            return false; // Break loop
          }
        });
      }
      
      if ($element && $element.length) {
        suggestionCount++;
        
        // Preserve original styling
        const originalStyle = $element.attr('style') || '';
        const originalClass = $element.attr('class') || '';
        
        // Create tracking structure
        const suggestionId = `suggestion-${Date.now()}-${suggestionCount}`;
        const originalSpan = `<span class="original-text" style="display:none" data-original="true">${suggestion.originalText}</span>`;
        const suggestedSpan = `<span class="suggested-text" data-suggestion-id="${suggestionId}">${suggestion.suggestedText}</span>`;
        
        // Replace content while preserving element structure
        $element.html(originalSpan + suggestedSpan);
        
        // Add tracking attributes
        $element.addClass('ai-suggestion');
        $element.attr('data-suggestion-id', suggestionId);
        $element.attr('data-suggestion-type', suggestion.type);
        $element.attr('data-confidence', suggestion.confidence);
        $element.attr('data-match-score', suggestion.matchScore);
        
        // Store suggestion metadata
        $element.attr('data-suggestion-meta', JSON.stringify({
          id: suggestionId,
          type: suggestion.type,
          confidence: suggestion.confidence,
          reason: suggestion.reason,
          timestamp: new Date().toISOString()
        }));
      }
    }
    
    // Add CSS for highlighting (only if not already present)
    if (!$('style#ai-suggestion-styles').length) {
      $('head').append(`
        <style id="ai-suggestion-styles">
          .ai-suggestion { 
            background-color: rgba(34, 197, 94, 0.2); 
            transition: background-color 0.3s ease;
          }
          .ai-suggestion.accepted { 
            background-color: transparent; 
          }
          .ai-suggestion.rejected { 
            background-color: rgba(239, 68, 68, 0.2); 
            text-decoration: line-through;
          }
          .ai-suggestion.pending {
            background-color: rgba(251, 191, 36, 0.2);
          }
          .original-text { display: none !important; }
          .suggested-text { display: inline; }
          .ai-suggestion.show-original .original-text { display: inline !important; }
          .ai-suggestion.show-original .suggested-text { display: none !important; }
        </style>
      `);
    }
    
    // Add suggestion summary
    $('body').prepend(`
      <div id="ai-suggestions-summary" style="display:none;">
        <data value="${suggestionCount}">${suggestionCount} suggestions applied</data>
      </div>
    `);
    
    return $.html();
  }

  /**
   * Accept a specific suggestion
   * @param {string} html - HTML with suggestions
   * @param {string} suggestionId - ID of suggestion to accept
   * @returns {string} - Updated HTML
   */
  acceptSuggestion(html, suggestionId) {
    const $ = cheerio.load(html);
    const $element = $(`[data-suggestion-id="${suggestionId}"]`);
    
    if ($element.length) {
      // Remove the original text span
      $element.find('.original-text').remove();
      
      // Update classes
      $element.removeClass('pending rejected');
      $element.addClass('accepted');
      
      // Update metadata
      const meta = JSON.parse($element.attr('data-suggestion-meta') || '{}');
      meta.status = 'accepted';
      meta.acceptedAt = new Date().toISOString();
      $element.attr('data-suggestion-meta', JSON.stringify(meta));
      
      // Keep only the suggested text
      const suggestedText = $element.find('.suggested-text').text();
      $element.text(suggestedText);
    }
    
    return $.html();
  }

  /**
   * Reject a specific suggestion
   * @param {string} html - HTML with suggestions
   * @param {string} suggestionId - ID of suggestion to reject
   * @returns {string} - Updated HTML
   */
  rejectSuggestion(html, suggestionId) {
    const $ = cheerio.load(html);
    const $element = $(`[data-suggestion-id="${suggestionId}"]`);
    
    if ($element.length) {
      // Show original text
      $element.addClass('rejected show-original');
      $element.removeClass('pending accepted');
      
      // Update metadata
      const meta = JSON.parse($element.attr('data-suggestion-meta') || '{}');
      meta.status = 'rejected';
      meta.rejectedAt = new Date().toISOString();
      $element.attr('data-suggestion-meta', JSON.stringify(meta));
      
      // Restore original text
      const originalText = $element.find('.original-text').text();
      $element.text(originalText);
      $element.removeClass('ai-suggestion');
    }
    
    return $.html();
  }

  /**
   * Apply bulk suggestion actions
   * @param {string} html - HTML with suggestions
   * @param {Array} actions - Array of {suggestionId, action: 'accept'|'reject'}
   * @returns {string} - Updated HTML
   */
  applyBulkSuggestionActions(html, actions) {
    let updatedHtml = html;
    
    for (const action of actions) {
      if (action.action === 'accept') {
        updatedHtml = this.acceptSuggestion(updatedHtml, action.suggestionId);
      } else if (action.action === 'reject') {
        updatedHtml = this.rejectSuggestion(updatedHtml, action.suggestionId);
      }
    }
    
    return updatedHtml;
  }

  /**
   * Accept all suggestions
   * @param {string} html - HTML with suggestions
   * @returns {string} - Updated HTML
   */
  acceptAllSuggestions(html) {
    const $ = cheerio.load(html);
    const actions = [];
    
    $('.ai-suggestion').each((i, el) => {
      const suggestionId = $(el).attr('data-suggestion-id');
      if (suggestionId) {
        actions.push({ suggestionId, action: 'accept' });
      }
    });
    
    return this.applyBulkSuggestionActions(html, actions);
  }

  /**
   * Reject all suggestions
   * @param {string} html - HTML with suggestions
   * @returns {string} - Updated HTML
   */
  rejectAllSuggestions(html) {
    const $ = cheerio.load(html);
    const actions = [];
    
    $('.ai-suggestion').each((i, el) => {
      const suggestionId = $(el).attr('data-suggestion-id');
      if (suggestionId) {
        actions.push({ suggestionId, action: 'reject' });
      }
    });
    
    return this.applyBulkSuggestionActions(html, actions);
  }

  /**
   * Revert all changes and restore original
   * @param {string} html - HTML with suggestions
   * @returns {string} - Original HTML
   */
  revertAllChanges(html) {
    const $ = cheerio.load(html);
    
    // Remove suggestion summary
    $('#ai-suggestions-summary').remove();
    
    // Process each suggestion element
    $('.ai-suggestion').each((i, el) => {
      const $el = $(el);
      const originalText = $el.find('.original-text').text();
      
      if (originalText) {
        // Restore original text
        $el.text(originalText);
      }
      
      // Remove suggestion classes and attributes
      $el.removeClass('ai-suggestion accepted rejected pending show-original');
      $el.removeAttr('data-suggestion-id');
      $el.removeAttr('data-suggestion-type');
      $el.removeAttr('data-confidence');
      $el.removeAttr('data-match-score');
      $el.removeAttr('data-suggestion-meta');
    });
    
    // Remove suggestion styles if no more suggestions
    if (!$('.ai-suggestion').length) {
      $('#ai-suggestion-styles').remove();
    }
    
    return $.html();
  }

  /**
   * Get suggestion statistics
   * @param {string} html - HTML with suggestions
   * @returns {Object} - Statistics about suggestions
   */
  getSuggestionStats(html) {
    const $ = cheerio.load(html);
    const stats = {
      total: 0,
      accepted: 0,
      rejected: 0,
      pending: 0,
      byType: {},
      byConfidence: {}
    };
    
    $('.ai-suggestion').each((i, el) => {
      const $el = $(el);
      stats.total++;
      
      // Count by status
      if ($el.hasClass('accepted')) stats.accepted++;
      else if ($el.hasClass('rejected')) stats.rejected++;
      else stats.pending++;
      
      // Count by type
      const type = $el.attr('data-suggestion-type') || 'unknown';
      stats.byType[type] = (stats.byType[type] || 0) + 1;
      
      // Count by confidence
      const confidence = $el.attr('data-confidence') || 'unknown';
      stats.byConfidence[confidence] = (stats.byConfidence[confidence] || 0) + 1;
    });
    
    return stats;
  }

  /**
   * Export final HTML with only accepted changes
   * @param {string} html - HTML with suggestions
   * @returns {string} - Clean HTML with accepted changes
   */
  exportFinalHtml(html) {
    const $ = cheerio.load(html);
    
    // Remove suggestion summary
    $('#ai-suggestions-summary').remove();
    
    // Clean up all suggestion elements
    $('.t').each((i, el) => {
      const $el = $(el);
      
      // If it's a rejected suggestion, restore original
      if ($el.hasClass('rejected')) {
        const originalText = $el.find('.original-text').text();
        if (originalText) {
          $el.text(originalText);
        }
      }
      
      // Remove all suggestion-related attributes and classes
      $el.removeClass('ai-suggestion accepted rejected pending show-original');
      $el.removeAttr('data-suggestion-id');
      $el.removeAttr('data-suggestion-type');
      $el.removeAttr('data-confidence');
      $el.removeAttr('data-match-score');
      $el.removeAttr('data-suggestion-meta');
      
      // Remove auto-generated IDs
      if ($el.attr('id') && $el.attr('id').startsWith('text-auto-')) {
        $el.removeAttr('id');
      }
    });
    
    // Remove suggestion styles
    $('#ai-suggestion-styles').remove();
    
    return $.html();
  }
}

module.exports = new HtmlParserService();